spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  batch:
    jdbc:
      initialize-schema: always

batch:
  loan-notification:
    cron: "0 0 9 * * *"

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}