apiVersion: v1
kind: Secret

metadata:
  name: library-secret
  namespace: library

type: Opaque

stringData:

  MYSQL_ROOT_PASSWORD: your_new_password

  JWT_SECRET_KEY: "k8aLxsxAeC/r5gmbdriGLbjZ3+vpHbkzdTbNWpQlIsc="

  JWT_EXPIRATION: "86400000"

